### ISSUE TITLE
Does Crash every 10 minutes

### ISSUE THREAD

**Issue by Ringeltier** [stephen304/castblock#14]
Currently I am using Docker 20.10.0 and the latest version of castblock.
Every 10 minutes the container crashes.
This causes that castblock is not able to block the ads until the container restarts.
Also it would be clever to implement a healthcheck
![image](https://user-images.githubusercontent.com/11855835/102230059-b4b69280-3eec-11eb-87d2-8bb1069be007.png)

**Comment by stephen304** [comment]
This seems like a bug in go-chromecast. Do you mind reporting it here? https://github.com/vishen/go-chromecast
