### ISSUE TITLE
Constant writing to disk

### ISSUE THREAD

**Issue by dine909** [stephen304/castblock#5]
There appears to be a constant stream of data being written to the disk at all times when castblock is running, this is on an Arm system booted off an SD card.

There are no casts running.
Kernel CPU usage is constant 100% when castblock is running
my `/tmp` mount is tmpfs

**Comment by stephen304** [comment]
Ah I just noticed this, castblock-state fills up continuously. I'll update when I get a chance to look at it

**Comment by stephen304** [comment]
@dine909 Not bad, a 2 character fix it seems. It should be fixed now, but cpu usage is expected to be high because of the chromecast polling. It no longer fills up /tmp/, but it should never have been writing to anywhere else.

Let me know if there are any other issues
